### ISSUE TITLE
Use Implicit Operators for assignment

### ISSUE THREAD

**Issue by MarqueIV** [ReactiveSoftware/Rx.Net.Plus#1]
In response to your statement "As C# does not support overloading of the assignment operator, it is impossible to assign a value directly to a variable." I think you can use the implicit operators for that.  If you add them to your type, you can implicitly convert from ints, bools, etc. to your RxInts, bools, etc.

As an example from their docs, take a look at this...

```
class Digit{

    public Digit(double d)
        => val = d;

    private readonly double val;

    // User-defined conversion from Digit to double
    public static implicit operator double(Digit d)
        => d.val;

    //  User-defined conversion from double to Digit
    public static implicit operator Digit(double d) 
        => new Digit(d);
}
```
With that, you can do this...

```
Digit myDigit = new Digit(4);

myDigit = 7; // Implicitly calls new Digit(7)

```
Won't that address the issue you're talking about?

M

**Comment by MarqueIV** [comment]
Actually, disregard. I see the issue with my thought. This would give you an entirely new instance, not update the existing one, so it wouldn't work as everything would still be subscribed to the now-replaced instance, not the new one.  Gotcha. My bad.  (I don't see a 'delete' so I can't remove this.)

**Comment by ReactiveSoftware** [comment]
Hi
First I am happy to see that Rx.Net.Plus is of interest.
Indeed I have thought a lot about this and u fortunately as you stated it is impossible.
Thanks anyway
