### ISSUE TITLE
RxVar.ListenTo should enable dispose of subscription

### ISSUE THREAD

**Issue by ybeapps** [ReactiveSoftware/Rx.Net.Plus#2]
ListenTo(obs) is just obs.subscribe(this)
but it returns void
If you return the IDisposable that subscribe returns, maybe it'll enable the disposal of the subscription

so I can define my RxVar.ListenTo.
And after some time, dispose the ListenTo, and initiate another one.
because currently I believe both run together

Thanks!
Yitzchak

**Comment by ReactiveSoftware** [comment]
Hi Yitzchak !!

Apart semantics, RxVar.ListenTo utilizes the built-in CancellationToken to dispose the subscription.
In case you are interested to dispose the subscription independently to CancellationToken, please use classic Subscribe

Thanks
